permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# Blogger's information
author: 
  name: H.Y. ZHAN
  email: zhanhuangying@gmail.com
  link: https://huangying-zhan.github.io/
  # weibo: 
  github: https://github.com/Huangying-Zhan
  # music: 
  # linkedin: 

# Website's inforamtion
title: Huangying's Blog
description: My personal blog
url: https://huangying-zhan.github.io/
rss_url: /pages/atom.xml

# gavatar profile picture and Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics setup
ga:
  # id: UA-54262064-1 
  # url: painterlin.com

# disqus setup
disqus:
  shortname: jim_zhan

# Auto activate a category
active: Technical

# The tags displaying on homepage, except the Newest
cates: 
  - Blog

# Name of some specific pages
locals:
  tags: Tags
  about: About
  newest: Newest
  archive: Archive